using UnityEngine;

public class PigUnit1 : BunnyUnit2
{
    [Header("MoneyGenerated")]
    public float moneyGenerated; // Gold generated per attack
    private float totalGeneratedByThisPig = 0f; // Track gold generated by this pig
    private static float totalGoldGenerated = 0f; // Shared across all pigs

    private const float MAX_GOLD_PER_PIG = 100f;
    private const float MAX_TOTAL_GOLD = 500f;


    public GameObject goldGeneratedEffect; // Effect to play when gold is generated, adding it separately to avoid spawning it despise the max gold being reached.

    protected override void Start()
    {
        base.Start();
        OnDeath += DisableGoldIndicator;
    }

    protected override void OnEnable()
    {
        base.OnEnable();
        totalGeneratedByThisPig = 0f;
    }

    void EnableGoldIndicator()
    {
        if (!transform.Find("GoldIndicator"))
            return;
        transform.Find("GoldIndicator").gameObject.SetActive(true);
    }

    void DisableGoldIndicator()
    {
        if (!transform.Find("GoldIndicator"))
            return;
        transform.Find("GoldIndicator").gameObject.SetActive(false);
    }
    public override void Attack()
    {
        base.Attack();
        if (CanGenerateMoney())
        {
            PlayHitSfx();
            GivePlayerMoney();
            Spawn(goldGeneratedEffect);
        }
    }
    public static void ResetGold()
    {
        totalGoldGenerated = 0f;
    }

    bool CanGenerateMoney()
    {
        return totalGoldGenerated < MAX_TOTAL_GOLD && totalGeneratedByThisPig < MAX_GOLD_PER_PIG;
    }
    void GivePlayerMoney()
    {
        if (!CanGenerateMoney())
            return;

        EnableGoldIndicator();
        poolObject.stageManager.GivePlayerMoney(moneyGenerated);

        totalGeneratedByThisPig += moneyGenerated;
        totalGoldGenerated += moneyGenerated;
        UpdateGoldIndicator();
    }

    // Make a method that will update a textmeshpro text with the total gold generated by this pig, the text is find in its childen, using this path "GoldIndicator/Canvas/Text (TMP)".
    public void UpdateGoldIndicator()
    {
        if (!transform.Find("GoldIndicator/Canvas/Text (TMP)"))
            return;

        TMPro.TextMeshProUGUI text = transform.Find("GoldIndicator/Canvas/Text (TMP)").GetComponent<TMPro.TextMeshProUGUI>();
        text.text = totalGeneratedByThisPig.ToString() + "$";
    }
}